language: php

branches:
  only:
    - master

cache:
  directories:
  - vendor
  - venv

before_install:
  - ./.travis/before_install.php
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz
  - sudo -H pip install -r requirements.txt
install: ./.travis/install.php
script: ./.travis/script.php

matrix:
  include:
    # old PHP versions with latest Symfony version
    - php: 5.4
      env: SYMFONY_VERSION=2.8.* # Symfony 3 doesn't support PHP 5.3
    - php: 5.6
      env: SYMFONY_VERSION=3.2.*
    - php: 7.0
      env: SYMFONY_VERSION=3.2.*
    - php: 7.1
      env: SYMFONY_VERSION=2.3.*
    - php: 7.1
      env: SYMFONY_VERSION=2.8.*
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*
    - php: 7.1
      env: SYMFONY_VERSION=4.0.*
    - php: 7.1
      env: SYMFONY_VERSION=dev-master
    # current PHP with all relevant Symfony versions
    - php: 7.2
      env: SYMFONY_VERSION=2.3.*
    - php: 7.2
      env: SYMFONY_VERSION=2.8.*
    - php: 7.2
      env: SYMFONY_VERSION=3.4.*
    - php: 7.2
      env: SYMFONY_VERSION=4.0.*
    - php: 7.2
      env: SYMFONY_VERSION=dev-master
    # experimental PHP with all relevant Symfony versions
    - php: nightly
      env: SYMFONY_VERSION=^4.0
    - php: nightly
      env: SYMFONY_VERSION=2.3.*
    - php: nightly
      env: SYMFONY_VERSION=2.8.*
    - php: nightly
      env: SYMFONY_VERSION=3.4.*
    - php: nightly
      env: SYMFONY_VERSION=4.0.*
    - php: nightly
      env: SYMFONY_VERSION=dev-master
  allow_failures:
    - php: 7.2 # allowed to fail until the project fully supports 7.2
    - php: nightly # 7.3 at present
    - env: SYMFONY_VERSION=dev-master
